### ISSUE TITLE
February 14, 2020 | Code-Review : The Poodles

### ISSUE THREAD

**Issue by sz16900** [jabichris/Newsweek-clone#4]
Great work on the Newsweek website:

- As you mentioned earlier, refactoring your code to accommodate for bootstrap classes is a must per requirements. I do not believe you need to fully customize it, just needs a few extra lines in your HTML. Great job, the website is looking fantastic.

**Comment by Meltrust** [comment]
Nice job, beautiful site.  Nice indentation too.  I don't know if that's an issue, but in your readme there's a link to the same repo but no live version.  Or install instructions.

**Comment by Flakster** [comment]
Good job @jabichris. In order to use the Bootstrap classes as much as possible, I suggest you give backgrounds and borders to some blocks, e.g. the Sponsored Insights, from the HTML by adding bg-light, border-secondary, etc classes, when they apply
